### ISSUE TITLE
and now for something completely different

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secret-stack#1]
while working on this, i started to think that maybe this is the wrong idea, or not the only way to do it.
since everything is "mounted" into the same api object, it feels like this could get messy.

here is another idea:

use the actor model: plugins would be a separate "actor", and you'd access it via a capability.
you could implement a plugin like thing by having a core actor create children, and give them names,
and then children could request access from core, who would give them caps or not, etc.

the neat thing about this is it would naturally apply to apis provided by plugins too.
so a app could request access to the photos app. this could (say) prompt the user, who could then give them that access, or you could give them another access to a dummp app. you could run multiple
photo apps, no problem.

How would this be implemented?

I think you'd need to have hierachical addresses for actors. for two actors on different machines to communicate you'd need ports/ips but for two actors on the same computer you wouldn't obviously.
if two actors on the same v8 content wanted to talk, they should be able to do so without going over the network... with a heirachical address you'd see that the prefix is the same and so just pass directly to that object. This could make it sufficiently light weight that an event emitter or say, input box could be an actor.

You'd need some sort of nestable multiplexer (of course, muxrpc is already nestable, but not as efficient as it could/should be)... lots that could be explored here... maybe will look into it later...

i guess the reason we ended up with muxrpc is that i have had lots of experience with rpc style, from working on/with multilevel.

**Comment by pfraze** [comment]
How do you feel about the remote require style? That's what electron went with https://github.com/atom/electron/blob/master/docs/api/remote.md

**Comment by dominictarr** [comment]
No i don't think this is a great idea. Or at least, it's only a good idea in a limited context.
the problem with remote require is it doesn't map to what is really happening. there is interprocess communictaion, but this is hiding that. This gives you a synchronous interface to the process on the otherside, this lie might be believable when those processes are close together, but not if they were over the network. 

whereas an actor model doesn't have this deceit.

 Also, the remote require doesn't really have a good way to manage instances, if you needed multilpe versions of a photo app, remote-require would become a very leaky abstraction, but actor model wouldn't.

**Comment by pfraze** [comment]
Well the only thing remote-require mandates is, you use a require statement to import an interface, and you give the interfaces simple string names, like modules have. The actual RPC calls could work exactly as muxrpc does now.

**Comment by dominictarr** [comment]
sure but the problem is that it paves over the problem of reconnects, so it wouldn't be suitable for connecting to remote instances like we do with rpc. I have thought about somehow removing the manifest requirement, but it would definately need to be async.

**Comment by pfraze** [comment]
Hmm, yeah. It definitely couldn't work like Electron does it, where you `require('remote').require('foo')`. Anyway, remote-require is just an API aesthetic, it's pretty surface level

**Comment by pfraze** [comment]
tristan tweeted something that I think about a lot regarding permission prompts:
https://twitter.com/tristanls/status/627116082432585728

and may relate here

**Comment by dominictarr** [comment]
I hate those things, it's like an ultermatim. you can either accept or reject the whole app, but you can't be like, okay i'll run you but you can't see my sms. I think what permissions would be reasonable should be part of an audit process. so users may collectively agree (by delegating to auditors they trust) on what permissions are reasonable for what that app does.
