### ISSUE TITLE
this.getAddress is not a function?

### ISSUE THREAD

**Issue by NHQ** [ssbc/secret-stack#15]
`this.getAddress is not a function`

I get this error when I try to call rpc.address(cb) in the connect callback.

**Comment by dominictarr** [comment]
my guess is that the rpc client's manifest does not have `"getAddress": "sync"`

**Comment by NHQ** [comment]
why does it show up on the rpc object?

I guess I don't need it tho, as I already must have had it to connect...

**Comment by dominictarr** [comment]
can you show the code to reproduce?

**Comment by NHQ** [comment]
```js
   'connect': function(peer, cb){ // peer.host is secret-stack address from another bot instance
          node.connect(peer.host, function(err, rpc){ // node is first argument of secret stack plugin init
            if(err) console.log(err) 
            rpc.address(function(err, data){ console.log(err}) // err here 
```

**Comment by NHQ** [comment]
it would be around [here](https://github.com/NHQ/dexbot/blob/master/core/index.js#L147)
