### ISSUE TITLE
Don't complain if the same plugin is used twice

### ISSUE THREAD

**Issue by maackle** [ssbc/secret-stack#19]
In my hot-reloading setup, it's annoying that when I reload my JS, I get the `plugin named:foo is already loaded` error. To get around it I am basically doing `create.plugins.splice(create.plugins.indexOf('foo'), 1)`, and then `use`ing my plugin again. It would be nice if `.use` would just silently reload a named plugin.

If that's undesirable, it would be nice to at least have something like `.unload()` which would be the inverse of `.use()`. Or `.reuse()` which would be idempotent.

I can create a PR for this if you chime in and let me know if any of those options sound good.

This is where I'm talking about: https://github.com/ssbc/secret-stack/blob/8c080d1d17f235f6b9a01dd986e1251aba3e2884/api.js#L71

**Comment by dominictarr** [comment]
hmm, so is it just reloading your code and not the whole sbot?
if this is only for development then your work arounds seem reasonable
