### ISSUE TITLE
More multiserver plugins?

### ISSUE THREAD

**Issue by staltz** [ssbc/secret-stack#20]
I'm designing in my mind a way of accommodating more servers types in scuttlebot, for instance Bluetooth but also DHT.

For instance, this could be one of the multiserver addresses:
`dht:uniquekeyinthedht~shs...`

Is changing secret-stack src the only way of accommodating more multiserver plugins, or is there another way of sideloading them?

If changing secret-stack src the only way, perhaps we should make the config object have a property to toggle the use of DHT or Bluetooth addresses.

**Comment by dominictarr** [comment]
yeah multiserver kinda has a plugin model, but I never got around to attaching it to sbot's plugins.
currently, youd need to change the secret-stack source, but best would be to change it to something such that plugins could provide new stream types.

**Comment by staltz** [comment]
This is actually done
