### ISSUE TITLE
multiserver config: incoming/outgoing -> server/client

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secret-stack#25]
@arj03 I get confused every time by incoming/outgoing what about changing it to server/client? most of the time we just say "server" and "client" so this seems more consistent. That said, I recommend we accept both (so the change is backwards compatible) but document server/client

**Comment by arj03** [comment]
But normally that is because you are talking about server/client as entities. In this case it is a connection which has 2 ends, so I'm not so sure the naming is clearer. I agree we often do use server/client.
