### ISSUE TITLE
Registering compound plugins

### ISSUE THREAD

**Issue by staltz** [ssbc/secret-stack#35]
I tried doing something with secret stack, and noticed I couldn't:

```js
require('ssb-server')
  .use(function initPluginAB(server) {
    server.use(pluginA);
    server.use(pluginB);
  })
```

In other words, I tried to create a plugin that contains two (or more) plugins, and registers multiple of them with `.use()`.

There are a few use cases for compound plugins:

- You could simultaneously register a legacy plugin alongside a modern plugin (e.g. old gossip plugin and new gossip plugin. This was my use case)
- You could create sets of predefined plugins, like e.g. `.use(require('ssb-standard-plugins'))`

This issue is a question: is it anyhow possible to use secret stack in a way that allows you to register multiple children plugins under a parent plugin? Then if not, would youse be open to a PR that supports this. For example, we could add `api.use = .....` somewhere here: https://github.com/ssbc/secret-stack/blob/16eb4d9b2ff7da3ac5ff89f616f38fcd5a4666f3/api.js#L46

**Comment by dominictarr** [comment]
currently, no. I was also thinking this would be needed to support a transition to a new ebt api.

what if you just pass an array to .use and it then calls .use on every item? (so if two things collide, same name) it just handles that as if it was added on their own.

**Comment by staltz** [comment]
> pass an array to .use

sounds good. Can I PR that?

**Comment by dominictarr** [comment]
@staltz sure!
